// Indian Primary Care Formulary — 110+ drugs
// Sources: CDSCO NLEM 2022, WHO EML 2023, current prescribing patterns
// Schema is in-memory; per-drug monographs for the TatvaCare app
//
// fields:
//   name        — generic (INN) name
//   brand       — common Indian brand names
//   class       — pharmacological class
//   schedule    — Indian drug schedule: H (prescription), H1 (schedule H1, more controlled), X (narcotic), OTC
//   rx_required — true if Rx is mandatory
//   adult_dose  — typical adult dosing
//   indications — array of { icd10, label } (the disease it treats)
//   mechanism   — short clinical mechanism
//   side_effects — most common adverse effects
//   ci          — contraindications
//   pregnancy   — pregnancy safety (A/B/C/D/X or 'safe'/'avoid'/'caution')
//   interactions — list of common interacting classes/drugs
//   keywords    — searchable keywords (synonyms, colloquial)

export const INDIAN_FORMULARY = [
  // ================== ANTIMICROBIALS ==================
  {
    name: 'Amoxicillin', brand: 'Mox, Amoxil, Novamox', class: 'Aminopenicillin antibiotic', schedule: 'H', rx_required: true,
    adult_dose: '250-500 mg TDS × 5-7 days',
    indications: [{icd10: 'J00', label: 'Acute URI'}, {icd10: 'J18.9', label: 'Pneumonia'}, {icd10: 'H66.9', label: 'Otitis media'}, {icd10: 'N39.0', label: 'UTI'}, {icd10: 'K02.1', label: 'Dental abscess'}],
    mechanism: 'Inhibits bacterial cell wall synthesis by binding penicillin-binding proteins',
    side_effects: 'Rash, diarrhea, nausea, GI upset; anaphylaxis in penicillin-allergic patients',
    ci: 'Penicillin allergy, infectious mononucleosis',
    pregnancy: 'safe (category B)',
    interactions: 'Methotrexate, oral contraceptives (reduced efficacy), probenecid, warfarin',
    keywords: ['amox', 'amoxy', 'broad spectrum penicillin'],
  },
  {
    name: 'Amoxicillin + Clavulanic acid', brand: 'Augmentin, Clavam, Moxikind-CV', class: 'β-lactam + β-lactamase inhibitor', schedule: 'H', rx_required: true,
    adult_dose: '500/125 mg TDS or 875/125 mg BD × 5-7 days',
    indications: [{icd10: 'J18.9', label: 'Pneumonia'}, {icd10: 'J06.9', label: 'Sinusitis'}, {icd10: 'L08.9', label: 'Skin/soft-tissue infection'}, {icd10: 'K81.9', label: 'Cholecystitis'}, {icd10: 'H66.9', label: 'Otitis media'}],
    mechanism: 'Clavulanic acid inhibits β-lactamase, restoring amoxicillin activity against resistant strains',
    side_effects: 'Diarrhea (very common), nausea, rash, candida overgrowth',
    ci: 'Penicillin allergy, cholestatic jaundice history',
    pregnancy: 'safe (category B)',
    interactions: 'Methotrexate, warfarin, OCP',
    keywords: ['augmentin', 'co-amoxiclav', 'amoxiclav'],
  },
  {
    name: 'Azithromycin', brand: 'Azithral, Zithromax, Azee', class: 'Macrolide antibiotic', schedule: 'H', rx_required: true,
    adult_dose: '500 mg OD × 3 days OR 1 g single dose (STI)',
    indications: [{icd10: 'J18.9', label: 'Atypical pneumonia'}, {icd10: 'J06.9', label: 'Sinusitis'}, {icd10: 'A09.0', label: 'Traveller\'s diarrhea'}, {icd10: 'H66.9', label: 'Otitis media'}, {icd10: 'A55', label: 'Chlamydia'}],
    mechanism: 'Binds 50S ribosomal subunit, inhibits bacterial protein synthesis',
    side_effects: 'Nausea, abdominal pain, QT prolongation (rare), hepatotoxicity',
    ci: 'Macrolide allergy, severe hepatic disease, known QT prolongation',
    pregnancy: 'safe (category B)',
    interactions: 'Antacids reduce absorption, warfarin, digoxin, ergot alkaloids, statins (esp. simvastatin)',
    keywords: ['azee', 'z-pack', 'Z', 'macrolide'],
  },
  {
    name: 'Ciprofloxacin', brand: 'Cifran, Ciplox, Ciprodac', class: 'Fluoroquinolone antibiotic', schedule: 'H', rx_required: true,
    adult_dose: '250-750 mg BD × 5-7 days (UTI 250-500 mg BD × 3 days)',
    indications: [{icd10: 'N39.0', label: 'UTI'}, {icd10: 'A09.0', label: 'Infectious diarrhea'}, {icd10: 'J18.9', label: 'Pneumonia (mild)'}, {icd10: 'K81.9', label: 'Biliary tract infection'}],
    mechanism: 'Inhibits DNA gyrase and topoisomerase IV; bactericidal',
    side_effects: 'Tendon rupture (esp. Achilles), QT prolongation, peripheral neuropathy, photosensitivity, hypoglycemia',
    ci: 'Pregnancy, children < 18, history of tendon disorders with FQ',
    pregnancy: 'avoid (category C)',
    interactions: 'Antacids, iron, calcium reduce absorption; warfarin; tizanidine (contraindicated); QT-prolonging drugs',
    keywords: ['cipro', 'floxacin', 'quinolone'],
  },
  {
    name: 'Doxycycline', brand: 'Doxy, Vibramycin, Doxicip', class: 'Tetracycline antibiotic', schedule: 'H', rx_required: true,
    adult_dose: '100 mg BD day 1, then 100 mg OD × 5-7 days',
    indications: [{icd10: 'J18.9', label: 'Atypical pneumonia'}, {icd10: 'A09.0', label: 'Traveller\'s diarrhea'}, {icd10: 'A55', label: 'Chlamydia'}, {icd10: 'A75.9', label: 'Rickettsial infections'}, {icd10: 'L70.0', label: 'Acne vulgaris'}],
    mechanism: 'Binds 30S ribosomal subunit, inhibits protein synthesis',
    side_effects: 'Photosensitivity, esophagitis, GI upset, teeth discoloration in children',
    ci: 'Pregnancy, children < 8, severe hepatic disease',
    pregnancy: 'avoid (category D)',
    interactions: 'Antacids, iron, calcium, dairy reduce absorption; warfarin; OCP',
    keywords: ['doxy', 'vibramycin', 'tetracycline'],
  },
  {
    name: 'Cefixime', brand: 'Taxim-O, Ceftas, Mahacef', class: '3rd-gen cephalosporin', schedule: 'H', rx_required: true,
    adult_dose: '200 mg BD × 5-7 days (or 400 mg OD)',
    indications: [{icd10: 'N39.0', label: 'UTI'}, {icd10: 'J18.9', label: 'Pneumonia'}, {icd10: 'H66.9', label: 'Otitis media'}, {icd10: 'A09.0', label: 'Bacterial dysentery'}],
    mechanism: 'Inhibits bacterial cell wall synthesis; resistant to many β-lactamases',
    side_effects: 'Diarrhea, nausea, headache, rash',
    ci: 'Cephalosporin hypersensitivity, severe penicillin allergy (cross-reactivity ~5-10%)',
    pregnancy: 'safe (category B)',
    interactions: 'Probenecid, warfarin, OCP',
    keywords: ['cefixime', 'ceftas', 'oral cephalosporin'],
  },
  {
    name: 'Metronidazole', brand: 'Flagyl, Metrogyl, Metrogyl IV', class: 'Nitroimidazole antimicrobial', schedule: 'H', rx_required: true,
    adult_dose: '400-500 mg TDS × 5-7 days (or 2 g single dose for trichomoniasis)',
    indications: [{icd10: 'A04.7', label: 'C. difficile colitis'}, {icd10: 'A59.0', label: 'Trichomoniasis'}, {icd10: 'A06.0', label: 'Amoebiasis'}, {icd10: 'K81.9', label: 'Anaerobic infections'}, {icd10: 'L08.9', label: 'Bacterial vaginosis'}],
    mechanism: 'Reduced to reactive nitro radical, damages bacterial DNA (anaerobes only)',
    side_effects: 'Metallic taste, nausea, disulfiram-like reaction with alcohol, peripheral neuropathy (long-term)',
    ci: 'Pregnancy 1st trimester, severe hepatic disease',
    pregnancy: 'avoid in 1st trimester (category B)',
    interactions: 'Alcohol (disulfiram reaction), warfarin, lithium, disulfiram',
    keywords: ['flagyl', 'metro', 'anaerobic'],
  },
  {
    name: 'Fluconazole', brand: 'Diflucan, Flucos, Zocon', class: 'Triazole antifungal', schedule: 'H', rx_required: true,
    adult_dose: '150 mg single dose (vaginal candidiasis), 200-400 mg OD × 2-4 weeks (systemic)',
    indications: [{icd10: 'B37.3', label: 'Vulvovaginal candidiasis'}, {icd10: 'B37.9', label: 'Candidiasis (oral/esophageal)'}, {icd10: 'B49', label: 'Systemic fungal infection'}],
    mechanism: 'Inhibits ergosterol synthesis (fungal cell membrane)',
    side_effects: 'Hepatotoxicity, GI upset, QT prolongation, headache',
    ci: 'Pregnancy (high dose), severe hepatic disease, co-administration with terfenadine',
    pregnancy: 'avoid (category C, high dose contraindicated)',
    interactions: 'Warfarin, phenytoin, rifampin (decreases fluconazole), QT-prolonging drugs',
    keywords: ['diflucan', 'azole antifungal', 'candidiasis'],
  },
  {
    name: 'Acyclovir', brand: 'Acivir, Zovirax, Herpex', class: 'Antiviral (guanosine analogue)', schedule: 'H', rx_required: true,
    adult_dose: '200-400 mg 5x/day × 5-7 days (herpes); 800 mg 5x/day × 7 days (zoster)',
    indications: [{icd10: 'B00.9', label: 'Herpes simplex'}, {icd10: 'B02.9', label: 'Herpes zoster (shingles)'}, {icd10: 'B00.1', label: 'Herpes labialis'}],
    mechanism: 'Inhibits viral DNA polymerase after phosphorylation by viral thymidine kinase',
    side_effects: 'Nephrotoxicity (IV, especially with rapid infusion), nausea, headache',
    ci: 'Severe renal impairment (dose adjust)',
    pregnancy: 'safe (category B)',
    interactions: 'Probenecid, nephrotoxic drugs (aminoglycosides, NSAIDs)',
    keywords: ['aciclovir', 'zovirax', 'antiviral'],
  },
  {
    name: 'Oseltamivir', brand: 'Tamiflu, Fluvir, Antiflu', class: 'Neuraminidase inhibitor', schedule: 'H', rx_required: true,
    adult_dose: '75 mg BD × 5 days (start within 48h of symptoms)',
    indications: [{icd10: 'J10.1', label: 'Influenza A/B'}],
    mechanism: 'Inhibits viral neuraminidase, prevents release of new virions',
    side_effects: 'Nausea, vomiting, headache (usually mild)',
    ci: 'Severe renal impairment (dose adjust)',
    pregnancy: 'safe (category B); consider benefits vs risk in severe flu',
    interactions: 'Live attenuated influenza vaccine (within 48h)',
    keywords: ['tamiflu', 'flu antiviral', 'H1N1'],
  },

  // ================== ANALGESICS / ANTIPYRETICS ==================
  {
    name: 'Paracetamol (Acetaminophen)', brand: 'Calpol, Crocin, Dolo, Tylenol', class: 'Non-opioid analgesic / antipyretic', schedule: 'OTC', rx_required: false,
    adult_dose: '500-1000 mg q6-8h (max 4 g/day)',
    indications: [{icd10: 'R50.9', label: 'Fever'}, {icd10: 'R51', label: 'Headache'}, {icd10: 'R52.1', label: 'Mild-moderate pain'}, {icd10: 'M79.1', label: 'Myalgia'}],
    mechanism: 'Inhibits CNS prostaglandin synthesis; weak peripheral COX inhibition',
    side_effects: 'Hepatotoxicity at >10 g/day, rare skin reactions (SJS)',
    ci: 'Severe hepatic impairment, active liver disease',
    pregnancy: 'safe (category A; first-line analgesic)',
    interactions: 'Alcohol (hepatotoxicity), warfarin (high dose), isoniazid',
    keywords: ['acetaminophen', 'crocin', 'dolo', 'calpol', 'PCM', 'tylenol', 'fever medicine'],
  },
  {
    name: 'Ibuprofen', brand: 'Brufen, Ibugesic, Advil', class: 'NSAID (propionic acid)', schedule: 'OTC', rx_required: false,
    adult_dose: '200-400 mg q6-8h (max 1200 mg/day OTC; 2400 mg/day Rx)',
    indications: [{icd10: 'R51', label: 'Headache'}, {icd10: 'M79.1', label: 'Myalgia'}, {icd10: 'M54.5', label: 'Low back pain'}, {icd10: 'M25.5', label: 'Joint pain'}, {icd10: 'N94.6', label: 'Dysmenorrhea'}, {icd10: 'R50.9', label: 'Fever'}],
    mechanism: 'Reversibly inhibits COX-1 and COX-2, reducing prostaglandin synthesis',
    side_effects: 'GI upset, ulcer, renal impairment, increased CV risk, fluid retention',
    ci: 'Active peptic ulcer, severe renal/hepatic impairment, 3rd trimester pregnancy, post-CABG',
    pregnancy: 'avoid 3rd trimester (category C; D in 3rd trimester)',
    interactions: 'Warfarin, ACE inhibitors, lithium, methotrexate, aspirin',
    keywords: ['brufen', 'NSAID', 'pain killer', 'fever medicine'],
  },
  {
    name: 'Diclofenac', brand: 'Voveran, Diclofenac, Zorvolex', class: 'NSAID (arylacetic acid)', schedule: 'H', rx_required: true,
    adult_dose: '25-50 mg BD-TDS (oral); 75 mg IM single dose',
    indications: [{icd10: 'M25.5', label: 'Joint pain'}, {icd10: 'M54.5', label: 'Back pain'}, {icd10: 'M79.1', label: 'Myalgia'}, {icd10: 'M17.9', label: 'Osteoarthritis'}, {icd10: 'G43.9', label: 'Migraine'}],
    mechanism: 'Preferentially inhibits COX-2 over COX-1',
    side_effects: 'GI upset/ulcer, hepatotoxicity, increased CV risk, fluid retention',
    ci: 'Active GI bleed, severe heart failure, post-CABG, 3rd trimester pregnancy',
    pregnancy: 'avoid 3rd trimester (category C; D in 3rd trimester)',
    interactions: 'Warfarin, ACEi, lithium, methotrexate, aspirin',
    keywords: ['voveran', 'NSAID', 'pain killer'],
  },
  {
    name: 'Naproxen', brand: 'Naprosyn, Xenobid, Aleve', class: 'NSAID (propionic acid, long-acting)', schedule: 'OTC (low dose)', rx_required: true,
    adult_dose: '250-500 mg BD (max 1000 mg/day)',
    indications: [{icd10: 'M25.5', label: 'Joint pain'}, {icd10: 'M54.5', label: 'Back pain'}, {icd10: 'N94.6', label: 'Dysmenorrhea'}, {icd10: 'R51', label: 'Headache'}],
    mechanism: 'Long-acting reversible COX inhibitor',
    side_effects: 'GI upset/ulcer, renal impairment, CV risk',
    ci: 'Active GI bleed, severe renal impairment, 3rd trimester',
    pregnancy: 'avoid 3rd trimester (category C)',
    interactions: 'Warfarin, ACEi, lithium, aspirin',
    keywords: ['naprosyn', 'NSAID', 'pain killer'],
  },
  {
    name: 'Aspirin (low dose)', brand: 'Disprin, Ecosprin, Asacard', class: 'Antiplatelet / NSAID', schedule: 'OTC', rx_required: false,
    adult_dose: '75-150 mg OD (antiplatelet); 300-600 mg q4-6h (analgesic)',
    indications: [{icd10: 'I20.9', label: 'Angina'}, {icd10: 'I63.9', label: 'Stroke (secondary prevention)'}, {icd10: 'I21.9', label: 'Post-MI'}, {icd10: 'R51', label: 'Headache (high dose)'}],
    mechanism: 'Irreversibly inhibits COX-1 in platelets; antiplatelet effect at low dose',
    side_effects: 'GI upset/ulcer, bleeding, tinnitus (toxicity), Reye syndrome in children',
    ci: 'Active bleed, peptic ulcer, children < 16 (viral infection — Reye), severe asthma',
    pregnancy: 'avoid 3rd trimester (category D)',
    interactions: 'Warfarin, ibuprofen (antagonizes), ACEi, methotrexate',
    keywords: ['ecosprin', 'disprin', 'low-dose aspirin', 'antiplatelet'],
  },
  {
    name: 'Tramadol', brand: 'Ultram, Tramacip, Tramazac', class: 'Atypical opioid analgesic (μ-agonist + SNRI)', schedule: 'H', rx_required: true,
    adult_dose: '50-100 mg q6-8h (max 400 mg/day)',
    indications: [{icd10: 'R52.1', label: 'Moderate-severe pain'}, {icd10: 'M25.5', label: 'Joint pain'}, {icd10: 'M79.1', label: 'Myalgia'}],
    mechanism: 'Weak μ-opioid agonist + serotonin and norepinephrine reuptake inhibitor',
    side_effects: 'Nausea, dizziness, constipation, seizures (high dose), serotonin syndrome with SSRIs',
    ci: 'Severe respiratory depression, MAOI use, opioid dependence, severe asthma',
    pregnancy: 'avoid (category C)',
    interactions: 'SSRIs/SNRIs (serotonin syndrome), MAOIs, alcohol, sedatives, carbamazepine',
    keywords: ['tramacip', 'ultram', 'opioid', 'pain killer'],
  },

  // ================== GI ==================
  {
    name: 'Omeprazole', brand: 'Omez, Omecip, Prilosec, Losec', class: 'Proton pump inhibitor (PPI)', schedule: 'OTC (low dose)', rx_required: true,
    adult_dose: '20-40 mg OD (before breakfast) × 4-8 weeks',
    indications: [{icd10: 'K21.9', label: 'GERD'}, {icd10: 'K29.7', label: 'Gastritis'}, {icd10: 'K27.9', label: 'Peptic ulcer'}, {icd10: 'K22.7', label: 'Barrett\'s esophagus'}],
    mechanism: 'Irreversibly inhibits H+/K+ ATPase in gastric parietal cells',
    side_effects: 'Headache, diarrhea, B12 deficiency (long-term), hypomagnesemia, increased fracture risk',
    ci: 'Concomitant use with rilpivirine, nelfinavir',
    pregnancy: 'safe (category C)',
    interactions: 'Clopidogrel (decreased activation), methotrexate, diazepam, phenytoin',
    keywords: ['PPI', 'omez', 'gastric', 'acid reflux', 'heartburn medicine'],
  },
  {
    name: 'Pantoprazole', brand: 'Pantocid, Pantop, Protonix', class: 'PPI', schedule: 'H', rx_required: true,
    adult_dose: '40 mg OD before breakfast',
    indications: [{icd10: 'K21.9', label: 'GERD'}, {icd10: 'K29.7', label: 'Gastritis'}, {icd10: 'K27.9', label: 'Peptic ulcer'}],
    mechanism: 'Irreversibly inhibits H+/K+ ATPase',
    side_effects: 'Headache, diarrhea, B12 deficiency (long-term)',
    ci: 'Hypersensitivity',
    pregnancy: 'safe (category B)',
    interactions: 'Methotrexate, atazanavir, ketoconazole/itraconazole (reduced absorption)',
    keywords: ['pantocid', 'PPI', 'acid reflux'],
  },
  {
    name: 'Ranitidine (withdrawn in many countries)', brand: 'Zinetac, Rantac (now mostly discontinued)', class: 'H2 receptor antagonist', schedule: 'OTC (recalled NDMA)', rx_required: false,
    adult_dose: '150 mg BD (was standard)',
    indications: [{icd10: 'K21.9', label: 'GERD (mild)'}, {icd10: 'K29.7', label: 'Gastritis (mild)'}],
    mechanism: 'Competitively blocks H2 receptors in gastric parietal cells',
    side_effects: 'NDMA contamination (carcinogenic) led to global withdrawal; constipation, headache',
    ci: 'Hypersensitivity',
    pregnancy: 'safe (category B)',
    interactions: 'Ketoconazole, atazanavir (reduced absorption)',
    keywords: ['zantac', 'H2 blocker', 'heartburn'],
  },
  {
    name: 'Famotidine', brand: 'Famocid, Pepcid, Topcid', class: 'H2 receptor antagonist', schedule: 'OTC', rx_required: false,
    adult_dose: '20-40 mg BD or 40 mg HS',
    indications: [{icd10: 'K21.9', label: 'GERD (mild)'}, {icd10: 'K29.7', label: 'Gastritis'}, {icd10: 'K27.9', label: 'Peptic ulcer'}],
    mechanism: 'Competitively blocks H2 receptors',
    side_effects: 'Headache, constipation, dizziness',
    ci: 'Hypersensitivity',
    pregnancy: 'safe (category B)',
    interactions: 'Ketoconazole, atazanavir (reduced absorption)',
    keywords: ['pepcid', 'H2 blocker', 'famocid'],
  },
  {
    name: 'Domperidone', brand: 'Domstal, Domperi, Motilium', class: 'Peripheral D2 antagonist (prokinetic)', schedule: 'H', rx_required: true,
    adult_dose: '10 mg TDS before meals (max 30 mg/day)',
    indications: [{icd10: 'R11', label: 'Nausea/vomiting'}, {icd10: 'K30', label: 'Functional dyspepsia'}, {icd10: 'K21.9', label: 'GERD (adjunct)'}],
    mechanism: 'Blocks D2 receptors in chemoreceptor trigger zone (CTZ) and upper GI tract',
    side_effects: 'Dry mouth, headache, QT prolongation, hyperprolactinemia',
    ci: 'Prolactinoma, severe hepatic impairment, known QT prolongation, GI hemorrhage',
    pregnancy: 'safe (category B; avoid in 1st trimester)',
    interactions: 'Ketoconazole, erythromycin (QT prolongation), anticholinergics',
    keywords: ['domstal', 'motilium', 'antiemetic', 'vomiting medicine'],
  },
  {
    name: 'Ondansetron', brand: 'Emeset, Zofran, Ondem', class: '5-HT3 antagonist (antiemetic)', schedule: 'H', rx_required: true,
    adult_dose: '4-8 mg TDS (chemo: 8 mg IV pre and q8h)',
    indications: [{icd10: 'R11', label: 'Nausea/vomiting (chemo, post-op)'}, {icd10: 'R11.2', label: 'Pregnancy nausea (severe)'}],
    mechanism: 'Blocks 5-HT3 receptors in CTZ and gut',
    side_effects: 'Constipation, headache, QT prolongation, serotonin syndrome',
    ci: 'Apomorphine use, severe hepatic impairment',
    pregnancy: 'safe (category B)',
    interactions: 'Apomorphine, QT-prolonging drugs, tramadol (serotonin syndrome)',
    keywords: ['zofran', 'emeset', 'antiemetic', 'vomiting medicine'],
  },
  {
    name: 'Loperamide', brand: 'Loperamide, Imodium, Lopamide', class: 'μ-opioid receptor agonist (gut)', schedule: 'OTC', rx_required: false,
    adult_dose: '4 mg initial, then 2 mg after each loose stool (max 16 mg/day)',
    indications: [{icd10: 'A09.0', label: 'Acute diarrhea (non-infectious)'}],
    mechanism: 'Slows intestinal transit, increases water/electrolyte absorption',
    side_effects: 'Constipation, abdominal cramps; rare cardiac events with high doses',
    ci: 'Acute dysentery, C. difficile colitis, children < 2',
    pregnancy: 'safe (category B)',
    interactions: 'P-gp inhibitors (quinidine, verapamil), QT-prolonging drugs',
    keywords: ['imodium', 'lopamide', 'anti-diarrheal', 'loose motion medicine'],
  },
  {
    name: 'Oral Rehydration Salts (ORS)', brand: 'Electral, ORS, WHO-ORS', class: 'Electrolyte/glucose solution', schedule: 'OTC', rx_required: false,
    adult_dose: '1 packet in 1 L water; sip 200-400 ml after each loose stool',
    indications: [{icd10: 'A09.0', label: 'Acute gastroenteritis'}, {icd10: 'K52.9', label: 'Diarrhea (any cause)'}],
    mechanism: 'Replaces water, sodium, potassium, glucose lost in diarrhea; glucose drives Na+ absorption',
    side_effects: 'Generally safe; rare hypernatremia if over-concentrated',
    ci: 'Ileus, intestinal obstruction',
    pregnancy: 'safe',
    interactions: 'None significant',
    keywords: ['electral', 'ORS', 'rehydration', 'loose motion'],
  },
  {
    name: 'Lactulose', brand: 'Lactulose, Duphalac, Evaculose', class: 'Osmotic laxative (synthetic disaccharide)', schedule: 'OTC', rx_required: false,
    adult_dose: '15-30 mL OD-BD',
    indications: [{icd10: 'K59.0', label: 'Constipation'}, {icd10: 'K72.9', label: 'Hepatic encephalopathy'}],
    mechanism: 'Osmotic retention of water in colon; also acidifies colon, traps ammonia',
    side_effects: 'Bloating, flatulence, abdominal cramps',
    ci: 'Galactosemia, intestinal obstruction',
    pregnancy: 'safe (category B)',
    interactions: 'May reduce activity of oral neomycin',
    keywords: ['duphalac', 'lactulose', 'constipation medicine'],
  },

  // ================== CARDIOVASCULAR ==================
  {
    name: 'Amlodipine', brand: 'Amlogard, Amlong, Stamlo', class: 'Calcium channel blocker (dihydropyridine)', schedule: 'H', rx_required: true,
    adult_dose: '5-10 mg OD',
    indications: [{icd10: 'I10', label: 'Essential hypertension'}, {icd10: 'I20.9', label: 'Angina (chronic stable)'}, {icd10: 'I50.9', label: 'Heart failure (rare)'}],
    mechanism: 'Blocks L-type calcium channels in vascular smooth muscle → vasodilation',
    side_effects: 'Peripheral edema, headache, flushing, dizziness, gingival hyperplasia',
    ci: 'Severe aortic stenosis, cardiogenic shock',
    pregnancy: 'safe (category C; preferred in pregnancy HTN)',
    interactions: 'Simvastatin (max 20 mg with amlodipine), grapefruit juice, CYP3A4 inhibitors',
    keywords: ['amlogard', 'amlong', 'stamlo', 'BP medicine', 'calcium channel blocker'],
  },
  {
    name: 'Telmisartan', brand: 'Telma, Telpres, Telmikind', class: 'Angiotensin II receptor blocker (ARB)', schedule: 'H', rx_required: true,
    adult_dose: '40-80 mg OD',
    indications: [{icd10: 'I10', label: 'Hypertension'}, {icd10: 'I50.9', label: 'Heart failure'}, {icd10: 'E11.9', label: 'Diabetic nephropathy (T2DM)'}],
    mechanism: 'Selectively blocks AT1 receptor, preventing angiotensin II vasoconstriction',
    side_effects: 'Dizziness, hyperkalemia, hypotension, increased creatinine (usually transient)',
    ci: 'Bilateral renal artery stenosis, pregnancy, hyperkalemia, severe hepatic impairment',
    pregnancy: 'CONTRAINDICATED (category D)',
    interactions: 'ACEi (avoid combo), potassium-sparing diuretics, NSAIDs (reduce effect), lithium',
    keywords: ['telma', 'ARB', 'BP medicine'],
  },
  {
    name: 'Losartan', brand: 'Losar, Cozaar, Losakind', class: 'ARB', schedule: 'H', rx_required: true,
    adult_dose: '50-100 mg OD-BD',
    indications: [{icd10: 'I10', label: 'Hypertension'}, {icd10: 'I50.9', label: 'Heart failure'}, {icd10: 'E11.9', label: 'Diabetic nephropathy'}, {icd10: 'I63.9', label: 'Stroke prevention (in HTN with LVH)'}],
    mechanism: 'Selectively blocks AT1 receptor',
    side_effects: 'Dizziness, hyperkalemia, hypotension, fatigue',
    ci: 'Bilateral renal artery stenosis, pregnancy, hyperkalemia',
    pregnancy: 'CONTRAINDICATED (category D)',
    interactions: 'ACEi (avoid), potassium-sparing diuretics, NSAIDs, lithium',
    keywords: ['losar', 'cozaar', 'ARB', 'BP medicine'],
  },
  {
    name: 'Enalapril', brand: 'Envas, Enace, Vasotec', class: 'ACE inhibitor', schedule: 'H', rx_required: true,
    adult_dose: '5-20 mg OD-BD',
    indications: [{icd10: 'I10', label: 'Hypertension'}, {icd10: 'I50.9', label: 'Heart failure'}, {icd10: 'E11.9', label: 'Diabetic nephropathy'}],
    mechanism: 'Inhibits ACE, reducing angiotensin II formation and bradykinin breakdown',
    side_effects: 'Dry cough (very common), hyperkalemia, angioedema, hypotension, taste disturbance',
    ci: 'Bilateral renal artery stenosis, pregnancy, angioedema history',
    pregnancy: 'CONTRAINDICATED (category D)',
    interactions: 'Potassium-sparing diuretics, lithium, NSAIDs, sacubitril',
    keywords: ['envas', 'vasotec', 'ACE inhibitor', 'BP medicine'],
  },
  {
    name: 'Atenolol', brand: 'Aten, Tenormin, Atenol', class: 'β1-selective blocker', schedule: 'H', rx_required: true,
    adult_dose: '25-100 mg OD',
    indications: [{icd10: 'I10', label: 'Hypertension'}, {icd10: 'I20.9', label: 'Angina'}, {icd10: 'I48.9', label: 'Atrial fibrillation (rate control)'}, {icd10: 'R00.0', label: 'Sinus tachycardia'}],
    mechanism: 'Competitive β1-adrenergic receptor antagonist',
    side_effects: 'Bradycardia, fatigue, cold extremities, bronchospasm (high dose), nightmares',
    ci: 'Severe bradycardia, heart block, severe asthma, decompensated heart failure',
    pregnancy: 'safe (category D; used in pregnancy HTN)',
    interactions: 'Verapamil/diltiazem (heart block), clonidine (rebound HTN), insulin (mask hypoglycemia)',
    keywords: ['aten', 'tenormin', 'beta blocker', 'BP medicine'],
  },
  {
    name: 'Metoprolol', brand: 'Metolar, Toprol, Betaloc', class: 'β1-selective blocker', schedule: 'H', rx_required: true,
    adult_dose: '25-200 mg OD-BD (extended release)',
    indications: [{icd10: 'I10', label: 'Hypertension'}, {icd10: 'I20.9', label: 'Angina'}, {icd10: 'I21.9', label: 'Post-MI'}, {icd10: 'I50.9', label: 'Heart failure (compensated)'}],
    mechanism: 'Competitive β1-adrenergic receptor antagonist',
    side_effects: 'Bradycardia, fatigue, dizziness, depression, bronchospasm',
    ci: 'Severe bradycardia, heart block, severe asthma, decompensated HF',
    pregnancy: 'safe (category C)',
    interactions: 'Verapamil/diltiazem, CYP2D6 inhibitors (paroxetine), clonidine',
    keywords: ['metolar', 'toprol', 'beta blocker', 'BP medicine'],
  },
  {
    name: 'Hydrochlorothiazide', brand: 'HCTZ, Aquazide, Esidrix', class: 'Thiazide diuretic', schedule: 'H', rx_required: true,
    adult_dose: '12.5-25 mg OD (morning)',
    indications: [{icd10: 'I10', label: 'Hypertension (first-line)'}, {icd10: 'I50.9', label: 'Heart failure (mild)'}],
    mechanism: 'Inhibits Na+/Cl- cotransporter in distal convoluted tubule',
    side_effects: 'Hypokalemia, hyponatremia, hyperuricemia (gout), hyperglycemia, photosensitivity',
    ci: 'Anuria, severe renal impairment, sulfa allergy (relative)',
    pregnancy: 'avoid (category D; older antihypertensives)',
    interactions: 'Lithium (toxicity), digoxin (hypokalemia), NSAIDs',
    keywords: ['HCTZ', 'thiazide', 'water pill', 'BP medicine'],
  },
  {
    name: 'Chlorthalidone', brand: 'Thalitone, Chlorthalidone, Clorpres', class: 'Thiazide-like diuretic (long-acting)', schedule: 'H', rx_required: true,
    adult_dose: '6.25-25 mg OD',
    indications: [{icd10: 'I10', label: 'Hypertension'}, {icd10: 'I50.9', label: 'Heart failure'}],
    mechanism: 'Same as HCTZ but longer acting (24-72h)',
    side_effects: 'Hypokalemia, hyperuricemia, hyperglycemia',
    ci: 'Anuria, sulfa allergy (relative)',
    pregnancy: 'avoid (category D)',
    interactions: 'Lithium, digoxin, NSAIDs',
    keywords: ['chlorthalidone', 'thalitone', 'long-acting thiazide', 'BP medicine'],
  },
  {
    name: 'Furosemide', brand: 'Lasix, Frusemide, Lasix', class: 'Loop diuretic', schedule: 'H', rx_required: true,
    adult_dose: '20-80 mg OD-BD (oral); 20-40 mg IV/IM for acute pulmonary edema',
    indications: [{icd10: 'I50.9', label: 'Heart failure (decompensated)'}, {icd10: 'N18.9', label: 'Chronic kidney disease (with edema)'}, {icd10: 'K76.6', label: 'Cirrhosis with ascites'}],
    mechanism: 'Inhibits Na+/K+/2Cl- cotransporter in thick ascending limb of loop of Henle',
    side_effects: 'Hypokalemia, hypomagnesemia, ototoxicity (high dose IV), volume depletion',
    ci: 'Anuria, severe electrolyte depletion',
    pregnancy: 'safe (category C; use only if needed)',
    interactions: 'Aminoglycosides (ototoxicity), lithium, digoxin, NSAIDs',
    keywords: ['lasix', 'frusemide', 'loop diuretic', 'water pill'],
  },
  {
    name: 'Spironolactone', brand: 'Aldactone, Spilactone, Spirono', class: 'Potassium-sparing diuretic (aldosterone antagonist)', schedule: 'H', rx_required: true,
    adult_dose: '25-100 mg OD (25 mg for HF)',
    indications: [{icd10: 'I50.9', label: 'Heart failure (with reduced EF)'}, {icd10: 'E26.0', label: 'Primary hyperaldosteronism'}, {icd10: 'L64.9', label: 'Androgenic alopecia (off-label)'}],
    mechanism: 'Competitive aldosterone antagonist in distal tubule',
    side_effects: 'Hyperkalemia, gynecomastia, menstrual irregularities, impotence',
    ci: 'Hyperkalemia, severe renal impairment, Addison disease',
    pregnancy: 'avoid (category C)',
    interactions: 'ACEi/ARBs (hyperkalemia), potassium supplements, NSAIDs',
    keywords: ['aldactone', 'MRA', 'potassium-sparing'],
  },
  {
    name: 'Atorvastatin', brand: 'Atorva, Storvas, Lipitor', class: 'HMG-CoA reductase inhibitor (statin)', schedule: 'H', rx_required: true,
    adult_dose: '10-80 mg HS',
    indications: [{icd10: 'E78.5', label: 'Hypercholesterolemia'}, {icd10: 'I21.9', label: 'Post-MI (secondary prevention)'}, {icd10: 'I63.9', label: 'Post-stroke (secondary prevention)'}],
    mechanism: 'Inhibits HMG-CoA reductase, reducing cholesterol synthesis in liver',
    side_effects: 'Myalgia, rhabdomyolysis (rare), elevated LFTs, GI upset',
    ci: 'Active liver disease, pregnancy, breastfeeding',
    pregnancy: 'CONTRAINDICATED (category X)',
    interactions: 'CYP3A4 inhibitors (clarithromycin, itraconazole, grapefruit), gemfibrozil, cyclosporine',
    keywords: ['atorva', 'storvas', 'lipitor', 'statin', 'cholesterol medicine'],
  },
  {
    name: 'Rosuvastatin', brand: 'Rosuvas, Crestor, Rosave', class: 'Statin (more potent, less CYP metabolism)', schedule: 'H', rx_required: true,
    adult_dose: '5-40 mg HS',
    indications: [{icd10: 'E78.5', label: 'Hypercholesterolemia'}, {icd10: 'I21.9', label: 'Post-MI (high-risk patients)'}],
    mechanism: 'Inhibits HMG-CoA reductase (less CYP3A4 metabolism = fewer drug interactions)',
    side_effects: 'Myalgia, rhabdomyolysis, elevated LFTs, proteinuria',
    ci: 'Active liver disease, pregnancy',
    pregnancy: 'CONTRAINDICATED (category X)',
    interactions: 'Cyclosporine, gemfibrozil, antacids (reduce absorption)',
    keywords: ['rosuvas', 'crestor', 'statin'],
  },
  {
    name: 'Clopidogrel', brand: 'Plavix, Clopilet, Clopivas', class: 'P2Y12 receptor antagonist (antiplatelet)', schedule: 'H', rx_required: true,
    adult_dose: '75 mg OD (loading: 300-600 mg)',
    indications: [{icd10: 'I21.9', label: 'Post-ACS / post-PCI'}, {icd10: 'I63.9', label: 'Stroke (secondary prevention)'}, {icd10: 'I20.9', label: 'Unstable angina'}],
    mechanism: 'Irreversibly blocks P2Y12 ADP receptor on platelets',
    side_effects: 'Bleeding, GI upset, rash, TTP (rare)',
    ci: 'Active bleeding, severe hepatic impairment',
    pregnancy: 'avoid (category B)',
    interactions: 'Omeprazole/esomeprazole (reduced activation - avoid combo), NSAIDs, warfarin',
    keywords: ['plavix', 'clopilet', 'antiplatelet', 'blood thinner'],
  },
  {
    name: 'Warfarin', brand: 'Warf, Acenocoumarol (Acitrom), Coumadin', class: 'Vitamin K antagonist (oral anticoagulant)', schedule: 'H', rx_required: true,
    adult_dose: '2-10 mg OD (titrate to INR 2-3)',
    indications: [{icd10: 'I48.9', label: 'Atrial fibrillation'}, {icd10: 'I26.9', label: 'PE/DVT (after heparin)'}, {icd10: 'I21.9', label: 'Post-MI (with LV thrombus)'}],
    mechanism: 'Inhibits vitamin K epoxide reductase, reducing clotting factors II, VII, IX, X',
    side_effects: 'Bleeding, skin necrosis (rare, with protein C deficiency), purple toe syndrome',
    ci: 'Active bleeding, severe hepatic disease, pregnancy (1st trimester — teratogenic)',
    pregnancy: 'CONTRAINDICATED (teratogenic); use LMWH instead',
    interactions: 'MANY: aspirin, NSAIDs, antibiotics (esp. macrolides, metronidazole, TMP-SMX), amiodarone, CYP2C9 inducers/inhibitors, vitamin K-rich foods',
    keywords: ['warfarin', 'acenocoumarol', 'coumadin', 'blood thinner', 'anticoagulant'],
  },
  {
    name: 'Digoxin', brand: 'Digoxin, Lanoxin, Dixin', class: 'Cardiac glycoside (positive inotrope)', schedule: 'H', rx_required: true,
    adult_dose: '0.125-0.25 mg OD (loading: 0.5-1 mg over 24h)',
    indications: [{icd10: 'I50.9', label: 'Heart failure (with AF)'}, {icd10: 'I48.9', label: 'AF (rate control)'}],
    mechanism: 'Inhibits Na+/K+ ATPase → increases intracellular Ca²⁺ → positive inotropy; also increases vagal tone',
    side_effects: 'Nausea, visual disturbances (yellow halos), arrhythmias (toxicity), bradycardia',
    ci: 'Ventricular fibrillation, severe bradycardia, 2nd/3rd-degree heart block',
    pregnancy: 'safe (category C)',
    interactions: 'Amiodarone, verapamil, diltiazem, diuretics (hypokalemia → toxicity), macrolides',
    keywords: ['lanoxin', 'dixin', 'digoxin', 'cardiac glycoside'],
  },
  {
    name: 'Isosorbide Mononitrate', brand: 'Imdur, Monotrate, Ismo', class: 'Organic nitrate (vasodilator)', schedule: 'H', rx_required: true,
    adult_dose: '20-60 mg OD-BD (asymmetric dosing to avoid tolerance)',
    indications: [{icd10: 'I20.9', label: 'Chronic stable angina'}, {icd10: 'I50.9', label: 'Heart failure (adjunct)'}],
    mechanism: 'Releases nitric oxide → activates guanylate cyclase → vasodilation (mainly venous)',
    side_effects: 'Headache, hypotension, flushing, tolerance (with continuous exposure)',
    ci: 'Concomitant PDE-5 inhibitors (sildenafil), severe hypotension, severe anemia',
    pregnancy: 'safe (category C)',
    interactions: 'Sildenafil/tadalafil, antihypertensives, alcohol',
    keywords: ['imdur', 'monotrate', 'ISMN', 'nitrate', 'angina medicine'],
  },
  {
    name: 'Glyceryl Trinitrate (GTN, sublingual)', brand: 'Sorbitrate, Anginil, Nitrocontin', class: 'Organic nitrate (rapid-acting)', schedule: 'H', rx_required: true,
    adult_dose: '0.5 mg sublingual, repeat q5min × 3 if needed',
    indications: [{icd10: 'I20.9', label: 'Acute angina attack'}, {icd10: 'I21.9', label: 'Acute coronary syndrome (initial)'}],
    mechanism: 'Same as isosorbide; rapid onset sublingually',
    side_effects: 'Headache, hypotension, reflex tachycardia',
    ci: 'Sildenafil use, severe hypotension, severe anemia',
    pregnancy: 'safe (category C)',
    interactions: 'PDE-5 inhibitors (severe hypotension), antihypertensives',
    keywords: ['GTN', 'nitroglycerin', 'sorbitrate', 'angina emergency medicine'],
  },
  {
    name: 'Propranolol', brand: 'Ciplar, Inderal, Betacap', class: 'Non-selective β-blocker', schedule: 'H', rx_required: true,
    adult_dose: '10-40 mg BD-TDS (cardiac); 10-40 mg TDS (migraine prophylaxis)',
    indications: [{icd10: 'I10', label: 'Hypertension'}, {icd10: 'I20.9', label: 'Angina'}, {icd10: 'G43.9', label: 'Migraine prophylaxis'}, {icd10: 'E05.9', label: 'Hyperthyroidism (symptomatic)'}, {icd10: 'F41.1', label: 'Anxiety (situational)'}],
    mechanism: 'Non-selective β-adrenergic antagonist',
    side_effects: 'Bradycardia, bronchospasm, cold extremities, fatigue, nightmares',
    ci: 'Severe asthma, severe bradycardia, heart block, decompensated HF',
    pregnancy: 'safe (category C)',
    interactions: 'Verapamil, insulin (masks hypoglycemia), clonidine',
    keywords: ['ciplar', 'inderal', 'beta blocker', 'propranolol', 'migraine medicine'],
  },

  // ================== DIABETES / ENDOCRINE ==================
  {
    name: 'Metformin', brand: 'Glycomet, Glucophage, Gluconorm, Metformin', class: 'Biguanide (insulin sensitizer)', schedule: 'H', rx_required: true,
    adult_dose: '500 mg BD-TDS (max 2 g/day), with meals',
    indications: [{icd10: 'E11.9', label: 'Type 2 diabetes mellitus'}, {icd10: 'E66.9', label: 'Obesity (with DM)'}, {icd10: 'E28.2', label: 'PCOS (off-label)'}],
    mechanism: 'Decreases hepatic gluconeogenesis, increases peripheral insulin sensitivity',
    side_effects: 'GI upset (very common), lactic acidosis (rare, with renal impairment), B12 deficiency',
    ci: 'eGFR < 30, acute heart failure, severe hepatic disease, alcoholism',
    pregnancy: 'safe (category B; first-line in gestational/preexisting DM in pregnancy)',
    interactions: 'Iodinated contrast (hold 48h), cimetidine, alcohol',
    keywords: ['glycomet', 'glucophage', 'gluconorm', 'diabetes medicine', 'sugar medicine'],
  },
  {
    name: 'Glimepiride', brand: 'Amaryl, Glimer, Glypride', class: 'Sulfonylurea (insulin secretagogue)', schedule: 'H', rx_required: true,
    adult_dose: '1-8 mg OD (before breakfast)',
    indications: [{icd10: 'E11.9', label: 'Type 2 DM (after metformin)'}],
    mechanism: 'Closes K+ channels in pancreatic β cells → depolarization → insulin release',
    side_effects: 'Hypoglycemia, weight gain, GI upset',
    ci: 'Type 1 DM, severe hepatic/renal impairment',
    pregnancy: 'avoid (category C; use insulin)',
    interactions: 'Sulfonylureas, alcohol, β-blockers (mask hypoglycemia), CYP2C9 inhibitors',
    keywords: ['amaryl', 'glimepiride', 'sulfonylurea', 'diabetes medicine'],
  },
  {
    name: 'Glipizide', brand: 'Glynase, Glide, Diabetrol', class: 'Sulfonylurea (short-acting)', schedule: 'H', rx_required: true,
    adult_dose: '2.5-20 mg OD-BD, 30 min before meals',
    indications: [{icd10: 'E11.9', label: 'Type 2 DM'}],
    mechanism: 'Same as glimepiride',
    side_effects: 'Hypoglycemia, weight gain',
    ci: 'Type 1 DM, severe hepatic/renal impairment',
    pregnancy: 'avoid (category C)',
    interactions: 'Same as glimepiride',
    keywords: ['glynase', 'glipizide', 'sulfonylurea'],
  },
  {
    name: 'Sitagliptin', brand: 'Januvia, Sitaglo, Istavel', class: 'DPP-4 inhibitor (gliptin)', schedule: 'H', rx_required: true,
    adult_dose: '100 mg OD',
    indications: [{icd10: 'E11.9', label: 'Type 2 DM (add-on or monotherapy)'}],
    mechanism: 'Inhibits DPP-4 → prolongs GLP-1 and GIP → glucose-dependent insulin release',
    side_effects: 'Nasopharyngitis, headache, pancreatitis (rare), joint pain',
    ci: 'Type 1 DM, severe renal impairment (dose adjust), ketoacidosis',
    pregnancy: 'avoid (limited data)',
    interactions: 'Few; may enhance sulfonylurea-induced hypoglycemia',
    keywords: ['januvia', 'gliptin', 'DPP-4 inhibitor', 'diabetes medicine'],
  },
  {
    name: 'Empagliflozin', brand: 'Jardiance, Empa, Glyxambi', class: 'SGLT2 inhibitor (gliflozin)', schedule: 'H', rx_required: true,
    adult_dose: '10-25 mg OD',
    indications: [{icd10: 'E11.9', label: 'Type 2 DM'}, {icd10: 'I50.9', label: 'Heart failure (with/without DM)'}, {icd10: 'N18.9', label: 'CKD (with DM)'}],
    mechanism: 'Inhibits SGLT2 in renal tubules → increases glucose excretion',
    side_effects: 'UTI, genital mycotic infections, euglycemic DKA, volume depletion, Fournier\'s gangrene (rare)',
    ci: 'Type 1 DM, eGFR < 20, severe renal impairment',
    pregnancy: 'avoid (2nd/3rd trimester)',
    interactions: 'Diuretics (volume depletion), insulin (hypoglycemia), rifampin (decreases efficacy)',
    keywords: ['jardiance', 'SGLT2', 'gliflozin', 'diabetes medicine'],
  },
  {
    name: 'Levothyroxine', brand: 'Eltroxin, Lethyrox, Thyronorm, Euthyrox', class: 'Thyroid hormone (T4)', schedule: 'H', rx_required: true,
    adult_dose: '25-200 mcg OD (on empty stomach, 30-60 min before breakfast)',
    indications: [{icd10: 'E03.9', label: 'Hypothyroidism (primary)'}, {icd10: 'E89.0', label: 'Post-thyroidectomy hypothyroidism'}, {icd10: 'E06.3', label: 'Hashimoto thyroiditis'}],
    mechanism: 'Replaces deficient endogenous thyroxine (T4); converted to T3 in periphery',
    side_effects: 'Palpitations, tremor, insomnia, weight loss (if over-replaced)',
    ci: 'Untreated adrenal insufficiency, recent MI, thyrotoxicosis',
    pregnancy: 'safe (category A; dose often increases in pregnancy)',
    interactions: 'Calcium, iron, antacids (reduce absorption - take 4h apart), warfarin, OCP',
    keywords: ['eltroxin', 'thyronorm', 'thyroid medicine', 'thyroxine'],
  },

  // ================== RESPIRATORY ==================
  {
    name: 'Salbutamol (Albuterol)', brand: 'Asthalin, Ventolin, Salbair', class: 'Short-acting β2-agonist (SABA)', schedule: 'H', rx_required: true,
    adult_dose: '2-4 mg TDS (oral); 100-200 mcg MDI 1-2 puffs q4-6h (inhaled)',
    indications: [{icd10: 'J45.9', label: 'Asthma (acute and maintenance rescue)'}, {icd10: 'J44.9', label: 'COPD (rescue)'}],
    mechanism: 'Activates β2-adrenergic receptors → bronchial smooth muscle relaxation',
    side_effects: 'Tremor, tachycardia, palpitations, hypokalemia (high dose)',
    ci: 'Severe cardiac arrhythmias',
    pregnancy: 'safe (category C; preferred in pregnancy asthma)',
    interactions: 'β-blockers (antagonize), MAOIs, tricyclics',
    keywords: ['asthalin', 'ventolin', 'SABA', 'inhaler', 'asthma medicine', 'puff'],
  },
  {
    name: 'Budesonide + Formoterol', brand: 'Foracort, Symbicort, Budamate', class: 'ICS + LABA combination', schedule: 'H', rx_required: true,
    adult_dose: '200/6 mcg 1-2 puffs BD (maintenance)',
    indications: [{icd10: 'J45.9', label: 'Asthma (maintenance)'}, {icd10: 'J44.9', label: 'COPD (maintenance)'}],
    mechanism: 'Budesonide = inhaled corticosteroid (anti-inflammatory); formoterol = long-acting β2-agonist (bronchodilation)',
    side_effects: 'Oral thrush, hoarseness, dysphonia; tremor, tachycardia (formoterol)',
    ci: 'Acute asthma exacerbation (rescue), severe hypersensitivity',
    pregnancy: 'safe (category C; budesonide preferred in pregnancy)',
    interactions: 'β-blockers, ketoconazole, ritonavir',
    keywords: ['foracort', 'symbicort', 'inhaler', 'asthma medicine', 'controller'],
  },
  {
    name: 'Montelukast', brand: 'Montair, Singulair, Montel', class: 'Leukotriene receptor antagonist', schedule: 'H', rx_required: true,
    adult_dose: '10 mg OD (HS)',
    indications: [{icd10: 'J45.9', label: 'Asthma (adjunct)'}, {icd10: 'J30.9', label: 'Allergic rhinitis'}],
    mechanism: 'Selectively blocks cysteinyl leukotriene-1 receptor',
    side_effects: 'Headache, abdominal pain, neuropsychiatric effects (rare: depression, suicidality in adults)',
    ci: 'Hypersensitivity',
    pregnancy: 'safe (category B)',
    interactions: 'Phenobarbital, rifampin (decrease levels)',
    keywords: ['montair', 'singulair', 'LTRA', 'asthma medicine', 'leukotriene'],
  },
  {
    name: 'Cetirizine', brand: 'Cetzine, Zyrtec, CTZ', class: '2nd-gen H1 antihistamine', schedule: 'OTC', rx_required: false,
    adult_dose: '10 mg OD',
    indications: [{icd10: 'J30.9', label: 'Allergic rhinitis'}, {icd10: 'L50.9', label: 'Urticaria'}, {icd10: 'L20.9', label: 'Atopic dermatitis (adjunct)'}],
    mechanism: 'Selective H1 receptor antagonist (peripheral, less CNS penetration)',
    side_effects: 'Drowsiness (less than 1st-gen), dry mouth',
    ci: 'Severe renal impairment (dose adjust)',
    pregnancy: 'safe (category B)',
    interactions: 'Few; alcohol (mild sedation)',
    keywords: ['cetzine', 'zyrtec', 'antihistamine', 'allergy medicine', 'cetirizine'],
  },
  {
    name: 'Levocetirizine', brand: 'Xyzal, Vozet, Teczine', class: '2nd-gen H1 antihistamine (active enantiomer)', schedule: 'OTC', rx_required: false,
    adult_dose: '5 mg OD',
    indications: [{icd10: 'J30.9', label: 'Allergic rhinitis'}, {icd10: 'L50.9', label: 'Urticaria'}],
    mechanism: 'Active R-enantiomer of cetirizine',
    side_effects: 'Drowsiness, dry mouth (less than 1st-gen)',
    ci: 'Severe renal impairment',
    pregnancy: 'avoid (limited data)',
    interactions: 'Alcohol, CNS depressants',
    keywords: ['xyzal', 'levocet', 'antihistamine', 'allergy medicine'],
  },
  {
    name: 'Fexofenadine', brand: 'Allegra, Fexova, Fexigra', class: '2nd-gen H1 antihistamine (non-sedating)', schedule: 'OTC', rx_required: false,
    adult_dose: '120-180 mg OD',
    indications: [{icd10: 'J30.9', label: 'Allergic rhinitis'}, {icd10: 'L50.9', label: 'Urticaria'}],
    mechanism: 'Selective H1 receptor antagonist; minimal CNS penetration',
    side_effects: 'Headache, GI upset, rare drowsiness',
    ci: 'Hypersensitivity',
    pregnancy: 'safe (category C)',
    interactions: 'Antacids (aluminum/magnesium - reduce absorption), fruit juices (decrease AUC)',
    keywords: ['allegra', 'fexo', 'antihistamine', 'allergy medicine'],
  },
  {
    name: 'Ambroxol', brand: 'Mucolite, Ambrodil, Mucosol', class: 'Mucolytic (ambroxol)', schedule: 'OTC', rx_required: false,
    adult_dose: '30 mg TDS (oral); 75 mg SR BD',
    indications: [{icd10: 'R05', label: 'Productive cough'}, {icd10: 'J18.9', label: 'Pneumonia (adjunct)'}],
    mechanism: 'Breaks down mucopolysaccharide fibers, stimulates surfactant production',
    side_effects: 'GI upset, headache, rare allergic reactions',
    ci: 'Hypersensitivity',
    pregnancy: 'avoid 1st trimester (category C)',
    interactions: 'None significant',
    keywords: ['mucolite', 'ambrodil', 'mucolytic', 'cough medicine'],
  },
  {
    name: 'Dextromethorphan', brand: 'Benadryl DR, Tussin-DM, Corex-DX', class: 'Antitussive (NMDA antagonist, σ-agonist)', schedule: 'OTC (cough syrups)', rx_required: false,
    adult_dose: '10-20 mg q4h (max 120 mg/day)',
    indications: [{icd10: 'R05', label: 'Dry non-productive cough'}],
    mechanism: 'Suppresses cough reflex by acting on the cough center in medulla',
    side_effects: 'Drowsiness, dizziness, nausea; abuse potential at high doses',
    ci: 'Use with MAOIs, productive cough',
    pregnancy: 'safe (category C)',
    interactions: 'MAOIs (serotonin syndrome), SSRIs, alcohol, opioids',
    keywords: ['DXM', 'corex', 'cough syrup', 'dry cough medicine'],
  },
  {
    name: 'Guaifenesin', brand: 'Mucinex, Glycodin, Benadryl CR', class: 'Expectorant', schedule: 'OTC', rx_required: false,
    adult_dose: '200-400 mg q4h (max 2400 mg/day)',
    indications: [{icd10: 'R05', label: 'Productive cough (loosen mucus)'}],
    mechanism: 'Increases respiratory tract fluid secretions, reducing mucus viscosity',
    side_effects: 'Nausea, vomiting, headache',
    ci: 'Chronic cough (smoking, asthma, emphysema)',
    pregnancy: 'safe (category C)',
    interactions: 'None significant',
    keywords: ['guaiphenesin', 'mucinex', 'expectorant', 'cough medicine'],
  },

  // ================== CNS / PSYCH ==================
  {
    name: 'Sertraline', brand: 'Zoloft, Daxid, Sertima', class: 'SSRI antidepressant', schedule: 'H', rx_required: true,
    adult_dose: '50-200 mg OD',
    indications: [{icd10: 'F32.9', label: 'Major depression'}, {icd10: 'F41.1', label: 'Generalized anxiety'}, {icd10: 'F40.0', label: 'OCD'}, {icd10: 'F43.1', label: 'PTSD'}],
    mechanism: 'Selectively inhibits serotonin reuptake at presynaptic neuron',
    side_effects: 'Nausea, sexual dysfunction, insomnia, jitteriness (first 2 weeks), hyponatremia (elderly)',
    ci: 'MAOI use (14-day washout), pimozide',
    pregnancy: 'paroxetine = avoid; sertraline is preferred (category C)',
    interactions: 'MAOIs (serotonin syndrome), NSAIDs (bleeding), warfarin, tamoxifen',
    keywords: ['zoloft', 'daxid', 'SSRI', 'antidepressant', 'depression medicine'],
  },
  {
    name: 'Escitalopram', brand: 'Lexapro, Nexito, S-Celepra', class: 'SSRI', schedule: 'H', rx_required: true,
    adult_dose: '10-20 mg OD',
    indications: [{icd10: 'F32.9', label: 'Major depression'}, {icd10: 'F41.1', label: 'Generalized anxiety'}],
    mechanism: 'S-enantiomer of citalopram; SSRI',
    side_effects: 'Nausea, sexual dysfunction, insomnia, QT prolongation (dose-dependent)',
    ci: 'MAOI use, pimozide',
    pregnancy: 'safe (category C; paroxetine preferred to avoid)',
    interactions: 'MAOIs, NSAIDs, warfarin, QT-prolonging drugs',
    keywords: ['lexapro', 'nexito', 'SSRI', 'antidepressant'],
  },
  {
    name: 'Alprazolam', brand: 'Alprax, Xanax, Alprazolam', class: 'Short-acting benzodiazepine', schedule: 'H1', rx_required: true,
    adult_dose: '0.25-1 mg TDS PRN (max 4 mg/day)',
    indications: [{icd10: 'F41.1', label: 'Anxiety (acute)'}, {icd10: 'F40.0', label: 'Panic disorder'}],
    mechanism: 'Potentiates GABA-A receptor activity (allosteric, increases Cl- conductance)',
    side_effects: 'Drowsiness, confusion, ataxia, dependence, withdrawal seizures',
    ci: 'Severe respiratory disease, sleep apnea, myasthenia gravis, narrow-angle glaucoma',
    pregnancy: 'CONTRAINDICATED (category D; cleft palate, floppy baby)',
    interactions: 'Alcohol, opioids (respiratory depression), CYP3A4 inhibitors',
    keywords: ['alprax', 'xanax', 'benzodiazepine', 'anxiety medicine', 'sedative'],
  },
  {
    name: 'Clonazepam', brand: 'Rivotril, Clonotril, Lonazep', class: 'Long-acting benzodiazepine', schedule: 'H1', rx_required: true,
    adult_dose: '0.5-2 mg BD-TDS (max 8 mg/day)',
    indications: [{icd10: 'F41.1', label: 'Anxiety'}, {icd10: 'G40.9', label: 'Epilepsy (adjunct)'}, {icd10: 'G47.0', label: 'REM sleep behavior disorder'}],
    mechanism: 'Potentiates GABA-A',
    side_effects: 'Drowsiness, dizziness, ataxia, dependence',
    ci: 'Severe respiratory disease, narrow-angle glaucoma',
    pregnancy: 'avoid (category D)',
    interactions: 'Alcohol, opioids, CYP3A4 inhibitors',
    keywords: ['rivotril', 'clonotril', 'lonazep', 'benzodiazepine', 'anxiety medicine'],
  },
  {
    name: 'Amitriptyline', brand: 'Tryptomer, Amitone, Elavil', class: 'Tricyclic antidepressant (TCA)', schedule: 'H', rx_required: true,
    adult_dose: '25-150 mg HS (depression); 10-25 mg HS (neuropathic pain/migraine prophylaxis)',
    indications: [{icd10: 'F32.9', label: 'Depression'}, {icd10: 'G43.9', label: 'Migraine prophylaxis'}, {icd10: 'G62.9', label: 'Neuropathic pain'}, {icd10: 'F51.0', label: 'Insomnia'}],
    mechanism: 'Inhibits reuptake of serotonin and norepinephrine; also has anticholinergic, antihistaminic, anti-α1 effects',
    side_effects: 'Dry mouth, constipation, urinary retention, blurred vision, orthostatic hypotension, weight gain, sedation, QT prolongation',
    ci: 'Recent MI, severe cardiac arrhythmia, narrow-angle glaucoma, MAOI use',
    pregnancy: 'avoid (category C)',
    interactions: 'MAOIs, anticholinergics, opioids, alcohol, CYP2D6 inhibitors',
    keywords: ['tryptomer', 'amitriptyline', 'TCA', 'antidepressant', 'neuropathic pain medicine'],
  },
  {
    name: 'Carbamazepine', brand: 'Tegretol, Carbamal, Mazetol', class: 'Sodium channel blocker (anticonvulsant)', schedule: 'H', rx_required: true,
    adult_dose: '100-200 mg BD-TDS (titrate up to 1600 mg/day)',
    indications: [{icd10: 'G40.9', label: 'Epilepsy (focal and generalized tonic-clonic)'}, {icd10: 'G50.0', label: 'Trigeminal neuralgia'}, {icd10: 'F31.9', label: 'Bipolar disorder (acute mania)'}],
    mechanism: 'Blocks voltage-gated sodium channels, stabilizing neuronal membranes',
    side_effects: 'Drowsiness, dizziness, ataxia, SIADH, agranulocytosis (rare), severe rash (SJS/TEN especially in Asians with HLA-B*1502), bone marrow suppression',
    ci: 'Bone marrow depression, MAOI use, severe hepatic disease, AV block',
    pregnancy: 'avoid (category D; neural tube defects)',
    interactions: 'MAJOR CYP3A4 inducer; reduces efficacy of OCP, warfarin, many drugs',
    keywords: ['tegretol', 'carbamazepine', 'anticonvulsant', 'epilepsy medicine'],
  },
  {
    name: 'Phenytoin', brand: 'Dilantin, Eptoin, Phenytoin', class: 'Sodium channel blocker (anticonvulsant)', schedule: 'H', rx_required: true,
    adult_dose: '100 mg TDS (or 15-20 mg/kg IV loading)',
    indications: [{icd10: 'G40.9', label: 'Epilepsy (generalized tonic-clonic, focal)'}, {icd10: 'R25.2', label: 'Status epilepticus (IV)'}],
    mechanism: 'Blocks voltage-gated sodium channels (use-dependent)',
    side_effects: 'Gingival hyperplasia, nystagmus, ataxia, hirsutism, folate deficiency, osteoporosis, severe rash',
    ci: 'Sinus bradycardia, heart block, severe hepatic disease',
    pregnancy: 'avoid (fetal hydantoin syndrome; category D)',
    interactions: 'CYP450 inducer (reduces OCP, warfarin, etc.), many',
    keywords: ['dilantin', 'eptoin', 'phenytoin', 'anticonvulsant', 'epilepsy medicine'],
  },
  {
    name: 'Valproate', brand: 'Valparin, Encorate, Valprol', class: 'Anticonvulsant (multi-mechanism)', schedule: 'H', rx_required: true,
    adult_dose: '200-600 mg BD-TDS (up to 60 mg/kg/day)',
    indications: [{icd10: 'G40.9', label: 'Epilepsy (generalized)'}, {icd10: 'F31.9', label: 'Bipolar disorder'}, {icd10: 'G43.9', label: 'Migraine prophylaxis'}],
    mechanism: 'Blocks Na+ channels, increases GABA levels, T-type Ca2+ channel inhibition',
    side_effects: 'Weight gain, tremor, alopecia, hepatotoxicity, thrombocytopenia, hyperammonemia, teratogenicity (NTD)',
    ci: 'Liver disease, urea cycle disorders, pregnancy (migraine indication)',
    pregnancy: 'CONTRAINDICATED for migraine; epilepsy = use lowest dose with informed consent (category D; NTD, decreased IQ)',
    interactions: 'CYP inhibitor; increases levels of phenytoin, carbamazepine, lamotrigine, warfarin',
    keywords: ['valparin', 'encorate', 'valproate', 'anticonvulsant', 'epilepsy medicine'],
  },
  {
    name: 'Levetiracetam', brand: 'Levipil, Keppra, Levera', class: 'Anticonvulsant (SV2A modulator)', schedule: 'H', rx_required: true,
    adult_dose: '500-1500 mg BD',
    indications: [{icd10: 'G40.9', label: 'Epilepsy (adjunct and monotherapy)'}],
    mechanism: 'Binds SV2A synaptic vesicle protein (modulates neurotransmitter release)',
    side_effects: 'Drowsiness, dizziness, behavioral changes (irritability, depression), headache',
    ci: 'Hypersensitivity',
    pregnancy: 'safe (category C; preferred AED in pregnancy)',
    interactions: 'Few; minimal hepatic metabolism',
    keywords: ['levipil', 'keppra', 'levetiracetam', 'anticonvulsant', 'epilepsy medicine'],
  },

  // ================== MISC ==================
  {
    name: 'Methotrexate (low dose)', brand: 'Folitrax, Mexate, Imutrex', class: 'Antimetabolite / DMARD', schedule: 'H', rx_required: true,
    adult_dose: '7.5-25 mg ONCE WEEKLY (with folic acid 5 mg weekly)',
    indications: [{icd10: 'M06.9', label: 'Rheumatoid arthritis'}, {icd10: 'L40.0', label: 'Psoriasis'}, {icd10: 'M32.9', label: 'SLE'}],
    mechanism: 'Inhibits dihydrofolate reductase (folate antagonist); also has anti-inflammatory effects at low dose',
    side_effects: 'Hepatotoxicity, bone marrow suppression, pulmonary toxicity, mucositis, teratogenicity',
    ci: 'Pregnancy (abortifacient, teratogenic), breastfeeding, severe hepatic/renal disease, active infection',
    pregnancy: 'CONTRAINDICATED (category X; highly teratogenic)',
    interactions: 'NSAIDs (reduce clearance), trimethoprim (additive anti-folate), alcohol (hepatotoxicity)',
    keywords: ['folitrax', 'methotrexate', 'DMARD', 'arthritis medicine', 'RA medicine'],
  },
  {
    name: 'Hydrochloroquine (HCQ)', brand: 'HCQS, Plaquenil, Hydroquin', class: 'DMARD / antimalarial', schedule: 'H', rx_required: true,
    adult_dose: '200-400 mg OD',
    indications: [{icd10: 'M32.9', label: 'SLE'}, {icd10: 'M06.9', label: 'Rheumatoid arthritis'}, {icd10: 'B54', label: 'Malaria (treatment & prophylaxis)'}],
    mechanism: 'Multiple: lysosomal pH modulation, TLR inhibition, immunomodulation',
    side_effects: 'Retinal toxicity (long-term, dose-related), QT prolongation, GI upset, skin pigmentation',
    ci: 'Pre-existing retinopathy, G6PD deficiency, severe hepatic disease',
    pregnancy: 'safe (category D; but actually safe in SLE/RA — risk of flare vs minor fetal risk)',
    interactions: 'QT-prolonging drugs, amiodarone, cyclosporine',
    keywords: ['HCQS', 'plaquenil', 'antimalarial', 'DMARD', 'SLE medicine', 'RA medicine'],
  },
  {
    name: 'Allopurinol', brand: 'Zyloric, Allopurinol, Allgoric', class: 'Xanthine oxidase inhibitor', schedule: 'H', rx_required: true,
    adult_dose: '100-900 mg OD (start low, titrate to serum uric acid <6 mg/dL)',
    indications: [{icd10: 'M10.9', label: 'Chronic gout'}, {icd10: 'M10.0', label: 'Acute gout (NOT for acute; start after flare)'}, {icd10: 'N20.0', label: 'Uric acid kidney stones'}],
    mechanism: 'Inhibits xanthine oxidase, reducing uric acid production',
    side_effects: 'Acute gout flare (on initiation — give prophylaxis), severe rash (SJS), hepatotoxicity',
    ci: 'Asymptomatic hyperuricemia, acute gout attack (without prophylaxis)',
    pregnancy: 'safe (category C)',
    interactions: 'Azathioprine (severe toxicity), mercaptopurine, warfarin, ampicillin (rash)',
    keywords: ['zyloric', 'allopurinol', 'gout medicine', 'uric acid medicine'],
  },
  {
    name: 'Febuxostat', brand: 'Febuget, Febuxor, Uloric', class: 'Xanthine oxidase inhibitor (non-purine)', schedule: 'H', rx_required: true,
    adult_dose: '40-80 mg OD',
    indications: [{icd10: 'M10.9', label: 'Chronic gout (especially if allopurinol intolerant)'}],
    mechanism: 'Same as allopurinol but non-purine structure',
    side_effects: 'Liver function abnormalities, nausea, joint pain, CV events (warning)',
    ci: 'Asymptomatic hyperuricemia, severe hepatic disease, concomitant azathioprine',
    pregnancy: 'avoid (limited data)',
    interactions: 'Azathioprine, mercaptopurine, theophylline',
    keywords: ['febuget', 'febuxostat', 'gout medicine'],
  },
  {
    name: 'Iron sucrose (IV)', brand: 'Orofer-S, Ferric, Encicarb', class: 'Parenteral iron', schedule: 'H', rx_required: true,
    adult_dose: '100-200 mg IV slow push or infusion (max 1000 mg/week)',
    indications: [{icd10: 'D50.9', label: 'Iron deficiency anemia (oral intolerance or severe)'}],
    mechanism: 'Replenishes iron stores; incorporated into hemoglobin',
    side_effects: 'Hypotension, hypersensitivity reactions, GI upset',
    ci: 'Anemia not due to iron deficiency, hypersensitivity',
    pregnancy: 'safe (category B; after 1st trimester if needed)',
    interactions: 'None significant with single IV dose',
    keywords: ['iron sucrose', 'IV iron', 'anemia medicine'],
  },
  {
    name: 'Ferrous sulfate (oral)', brand: 'Fefol, Livogen, Orofer', class: 'Oral iron supplement', schedule: 'OTC', rx_required: false,
    adult_dose: '200 mg BD-TDS (≈ 60-100 mg elemental Fe/day)',
    indications: [{icd10: 'D50.9', label: 'Iron deficiency anemia'}],
    mechanism: 'Provides elemental iron for hemoglobin synthesis',
    side_effects: 'GI upset, constipation, dark stools',
    ci: 'Hemochromatosis, hemosiderosis, repeated transfusions',
    pregnancy: 'safe (category A; standard in pregnancy)',
    interactions: 'Calcium, antacids, tea, coffee reduce absorption; vitamin C increases; tetracyclines (reduced absorption)',
    keywords: ['livogen', 'fefol', 'iron tablet', 'anemia medicine'],
  },
  {
    name: 'Folic acid', brand: 'Folvite, Foline, Folat', class: 'B vitamin (folate)', schedule: 'OTC', rx_required: false,
    adult_dose: '5 mg OD (therapeutic); 400-800 mcg OD (prevention in pregnancy)',
    indications: [{icd10: 'D52.0', label: 'Folate deficiency anemia'}, {icd10: 'O26.9', label: 'Pregnancy supplementation'}, {icd10: 'Z00.0', label: 'Pre-conception (NTD prevention)'}],
    mechanism: 'Essential cofactor for DNA synthesis and methylation',
    side_effects: 'Generally safe; rare GI upset, masks B12 deficiency',
    ci: 'B12 deficiency (masks neurologic damage), pernicious anemia',
    pregnancy: 'safe (category A; first-line prevention of NTD)',
    interactions: 'Methotrexate (antagonizes), phenytoin, sulfasalazine, TMP-SMX',
    keywords: ['folvite', 'folic', 'pregnancy vitamin', 'folate'],
  },
  {
    name: 'Cyanocobalamin (B12)', brand: 'Methycobal, Nurokind, B12', class: 'Vitamin B12', schedule: 'OTC', rx_required: false,
    adult_dose: '1 mg IM weekly × 4-6 weeks, then monthly (pernicious anemia); 1-2 mg oral daily',
    indications: [{icd10: 'D51.0', label: 'Vitamin B12 deficiency (pernicious anemia)'}, {icd10: 'G62.9', label: 'Peripheral neuropathy (with B12 deficiency)'}],
    mechanism: 'Essential for myelin synthesis, DNA synthesis, red cell formation',
    side_effects: 'Generally safe; rare hypersensitivity',
    ci: 'Hypersensitivity, hereditary optic nerve atrophy (Leber disease)',
    pregnancy: 'safe (category C)',
    interactions: 'Chloramphenicol, omeprazole, metformin (may reduce B12 levels)',
    keywords: ['methycobal', 'nurokind', 'B12', 'neurobion'],
  },
  {
    name: 'Vitamin D3 (Cholecalciferol)', brand: 'D-Rise, Uprise-D3, Tayo-D3', class: 'Vitamin D supplement', schedule: 'OTC', rx_required: false,
    adult_dose: '1000-60000 IU weekly (loading); 1000-2000 IU daily (maintenance)',
    indications: [{icd10: 'E55.9', label: 'Vitamin D deficiency'}, {icd10: 'M81.0', label: 'Osteoporosis (with calcium)'}],
    mechanism: 'Increases calcium and phosphate absorption; essential for bone health',
    side_effects: 'Hypercalcemia (very high dose), nephrocalcinosis',
    ci: 'Hypercalcemia, hypervitaminosis D, sarcoidosis',
    pregnancy: 'safe (category C)',
    interactions: 'Thiazides, anticonvulsants (reduce levels), cholestyramine',
    keywords: ['D-Rise', 'cholecalciferol', 'vitamin D', '60k'],
  },
  {
    name: 'Calcium carbonate', brand: 'Shelcal, CCM, CCM With Vitamin D3', class: 'Calcium supplement', schedule: 'OTC', rx_required: false,
    adult_dose: '500-1000 mg elemental Ca/day',
    indications: [{icd10: 'E58', label: 'Calcium deficiency'}, {icd10: 'M81.0', label: 'Osteoporosis (with vitamin D)'}],
    mechanism: 'Provides elemental calcium for bone and cellular function',
    side_effects: 'Constipation, hypercalcemia, kidney stones',
    ci: 'Hypercalcemia, calcium kidney stones (relative)',
    pregnancy: 'safe',
    interactions: 'Tetracyclines, quinolones, iron, levothyroxine (reduce absorption)',
    keywords: ['shelcal', 'calcium', 'cal tablet'],
  },
  {
    name: 'Ipratropium bromide', brand: 'Ipravent, Atrovent, Duolin (with salbutamol)', class: 'Short-acting antimuscarinic (SAMA)', schedule: 'H', rx_required: true,
    adult_dose: '2-4 puffs q6h (MDI); 500 mcg neb q6-8h',
    indications: [{icd10: 'J44.9', label: 'COPD'}, {icd10: 'J45.9', label: 'Asthma (adjunct in exacerbation)'}],
    mechanism: 'Muscarinic antagonist in airways, blocks vagally-mediated bronchoconstriction',
    side_effects: 'Dry mouth, urinary retention, constipation, blurred vision',
    ci: 'Hypersensitivity to atropine',
    pregnancy: 'safe (category B)',
    interactions: 'Anticholinergics (additive effects)',
    keywords: ['ipravent', 'atrovent', 'inhaler', 'duolin', 'COPD medicine'],
  },
  {
    name: 'Tiotropium', brand: 'Spiriva, Tiova', class: 'Long-acting antimuscarinic (LAMA)', schedule: 'H', rx_required: true,
    adult_dose: '18 mcg OD (HandiHaler) or 2.5 mcg/puff (Respimat) OD',
    indications: [{icd10: 'J44.9', label: 'COPD (maintenance)'}, {icd10: 'J45.9', label: 'Asthma (severe, add-on)'}],
    mechanism: 'Long-acting M3 muscarinic receptor antagonist',
    side_effects: 'Dry mouth, urinary retention, constipation',
    ci: 'Hypersensitivity, narrow-angle glaucoma',
    pregnancy: 'safe (category C)',
    interactions: 'Anticholinergics',
    keywords: ['spiriva', 'tiova', 'LAMA', 'COPD medicine', 'inhaler'],
  },
  {
    name: 'Cough syrup (dextromethorphan + phenylephrine + CPM)', brand: 'Corex-DX, Benadryl CR, Ascoril-D', class: 'Combination antitussive + decongestant + antihistamine', schedule: 'OTC', rx_required: false,
    adult_dose: '5-10 mL TDS',
    indications: [{icd10: 'R05', label: 'Dry cough with congestion'}],
    mechanism: 'Dextromethorphan = cough suppress; phenylephrine = α1 vasoconstrictor (nasal); chlorpheniramine = H1 antagonist',
    side_effects: 'Drowsiness, dry mouth, urinary retention, hypertension',
    ci: 'Hypertension (phenylephrine), MAOI use, children < 2',
    pregnancy: 'avoid (category C; OTC drug concerns)',
    interactions: 'MAOIs, antihypertensives, alcohol, sedatives',
    keywords: ['corex', 'benadryl', 'ascoril', 'cough syrup', 'cold syrup'],
  },
  {
    name: 'Azithromycin + Fluconazole + Secnidazole (combination kit)', brand: 'Azee-Azee, Cz-3, Combo kits', class: 'Combination antimicrobial kit', schedule: 'H', rx_required: true,
    adult_dose: 'Azithromycin 1g + Fluconazole 150mg + Secnidazole 2g single dose (varies by kit)',
    indications: [{icd10: 'A59.0', label: 'Trichomoniasis + candidiasis combo'}, {icd10: 'N76.0', label: 'Mixed vaginal infection'}],
    mechanism: 'Combination antibacterial + antifungal + antiprotozoal',
    side_effects: 'Nausea, metallic taste, hepatotoxicity (rare)',
    ci: 'Hypersensitivity, severe hepatic disease, pregnancy 1st trimester',
    pregnancy: 'avoid (category C; especially secnidazole)',
    interactions: 'See individual drugs',
    keywords: ['combo kit', 'cz3', 'trichomoniasis kit', 'vaginal kit'],
  },
  {
    name: 'Secnidazole', brand: 'Secnil, Seczole, Entosec', class: '5-nitroimidazole (antiprotozoal)', schedule: 'H', rx_required: true,
    adult_dose: '2 g single dose',
    indications: [{icd10: 'A06.0', label: 'Amoebiasis'}, {icd10: 'A59.0', label: 'Trichomoniasis'}, {icd10: 'A04.7', label: 'Giardiasis'}],
    mechanism: 'Same as metronidazole; longer half-life allows single-dose therapy',
    side_effects: 'Metallic taste, nausea, headache',
    ci: 'Pregnancy 1st trimester, hypersensitivity to nitroimidazoles',
    pregnancy: 'avoid 1st trimester',
    interactions: 'Alcohol (disulfiram reaction), warfarin, lithium',
    keywords: ['secnil', 'secnidazole', 'antiprotozoal'],
  },
  {
    name: 'Albendazole', brand: 'Albenza, Almex, Bandy', class: 'Anthelmintic (benzimidazole)', schedule: 'OTC', rx_required: false,
    adult_dose: '400 mg single dose (most helminths); 400 mg BD × 7-14 days (hydatid, neurocysticercosis)',
    indications: [{icd10: 'B77.9', label: 'Ascariasis (roundworm)'}, {icd10: 'B76.9', label: 'Hookworm'}, {icd10: 'B79', label: 'Trichuriasis (whipworm)'}, {icd10: 'B68.9', label: 'Taeniasis (tapeworm)'}],
    mechanism: 'Inhibits tubulin polymerization in helminths; depletes glucose uptake',
    side_effects: 'GI upset, hepatotoxicity, leukopenia, alopecia (high dose)',
    ci: 'Pregnancy (teratogenic), breastfeeding, ocular cysticercosis',
    pregnancy: 'CONTRAINDICATED (category X)',
    interactions: 'Dexamethasone, praziquantel (increase albendazole levels), cimetidine',
    keywords: ['albendazole', 'almex', 'bandy', 'deworming', 'worm medicine'],
  },
  {
    name: 'Ivermectin', brand: 'Ivecop, Iverheal, Ivermectol', class: 'Antiparasitic (avermectin)', schedule: 'H', rx_required: true,
    adult_dose: '150-200 mcg/kg single dose (onchocerciasis, scabies); repeat in 1-2 weeks',
    indications: [{icd10: 'B73', label: 'Onchocerciasis (river blindness)'}, {icd10: 'B86', label: 'Scabies (topical/oral)'}, {icd10: 'B76.9', label: 'Strongyloidiasis'}],
    mechanism: 'Binds glutamate-gated Cl- channels in invertebrates, paralyzing parasites',
    side_effects: 'Mazzotti reaction (in onchocerciasis), pruritus, fever, lymphadenopathy',
    ci: 'Pregnancy, breastfeeding, children < 5 (<15 kg)',
    pregnancy: 'CONTRAINDICATED',
    interactions: 'CYP3A4 substrates',
    keywords: ['ivermectin', 'ivecop', 'scabies medicine'],
  },
  {
    name: 'Hydroxychloroquine (SLE)', brand: 'HCQS 200, Plaquenil', class: 'DMARD / antimalarial', schedule: 'H', rx_required: true,
    adult_dose: '200-400 mg OD (max 6.5 mg/kg/day)',
    indications: [{icd10: 'M32.9', label: 'SLE'}, {icd10: 'M32.10', label: 'SLE with organ involvement'}],
    mechanism: 'Immunomodulatory; inhibits TLR signaling, modifies antigen presentation',
    side_effects: 'Retinopathy (cumulative dose), GI upset, skin hyperpigmentation, QT prolongation',
    ci: 'Pre-existing retinopathy, severe hepatic disease, G6PD deficiency',
    pregnancy: 'safe in pregnancy SLE/RA (continued use reduces flare)',
    interactions: 'QT-prolonging drugs, amiodarone, cyclosporine',
    keywords: ['HCQS', 'plaquenil', 'SLE medicine', 'malaria medicine'],
  },
  {
    name: 'Prednisolone', brand: 'Omnacortil, Wysolone, Predone', class: 'Synthetic glucocorticoid', schedule: 'H', rx_required: true,
    adult_dose: '5-60 mg OD (lowest effective dose, shortest duration)',
    indications: [{icd10: 'J45.9', label: 'Severe asthma (exacerbation)'}, {icd10: 'M32.9', label: 'SLE (flare)'}, {icd10: 'M06.9', label: 'Rheumatoid arthritis (flare)'}, {icd10: 'L20.9', label: 'Severe eczema'}],
    mechanism: 'Binds glucocorticoid receptor → broad anti-inflammatory and immunosuppressive effects',
    side_effects: 'Weight gain, hyperglycemia, osteoporosis, cataracts, mood changes, adrenal suppression (long-term), immunosuppression, Cushingoid',
    ci: 'Systemic infection (unless covered), live vaccines',
    pregnancy: 'safe (category C; use if needed)',
    interactions: 'NSAIDs (GI bleed), vaccines, CYP3A4 inducers, warfarin, antidiabetics',
    keywords: ['omnacortil', 'wysolone', 'prednisolone', 'steroid', 'PCS'],
  },
  {
    name: 'Doxycycline + Lactobacillus', brand: 'Doxycycline-LB, M-Tetra', class: 'Tetracycline antibiotic + probiotic', schedule: 'H', rx_required: true,
    adult_dose: 'Doxycycline 100 mg BD + Lactic acid bacillus (varies by brand)',
    indications: [{icd10: 'A09.0', label: 'Diarrhea with antibiotic cover'}],
    mechanism: 'Antibiotic + probiotic to prevent antibiotic-associated diarrhea',
    side_effects: 'See doxycycline; less GI upset with probiotic',
    ci: 'Pregnancy, children < 8',
    pregnancy: 'avoid',
    interactions: 'See doxycycline',
    keywords: ['doxy-lb', 'doxycycline combo', 'antidiarrheal antibiotic'],
  },
  {
    name: 'Clotrimazole (topical)', brand: 'Candid, Clotrimazole, Surfaz', class: 'Imidazole antifungal (topical)', schedule: 'OTC', rx_required: false,
    adult_dose: 'Apply BD-TDS × 2-4 weeks (skin); single dose (vaginal)',
    indications: [{icd10: 'B35.9', label: 'Dermatophytosis (ringworm)'}, {icd10: 'B37.9', label: 'Candidiasis (cutaneous/vulvovaginal)'}],
    mechanism: 'Inhibits ergosterol synthesis in fungal cell membrane',
    side_effects: 'Local irritation, allergic reaction',
    ci: 'Hypersensitivity',
    pregnancy: 'safe (topical)',
    interactions: 'None significant (topical)',
    keywords: ['candid', 'clotrimazole', 'antifungal cream', 'ringworm cream'],
  },
  {
    name: 'Mupirocin', brand: 'T-Bact, Mupinase, Mupirocin', class: 'Topical antibiotic (pseudomonic acid A)', schedule: 'H', rx_required: true,
    adult_dose: 'Apply TDS × 5-14 days',
    indications: [{icd10: 'L08.9', label: 'Impetigo'}, {icd10: 'L02.9', label: 'Folliculitis (mild)'}, {icd10: 'L73.8', label: 'Erythrasma'}],
    mechanism: 'Inhibits bacterial isoleucyl-tRNA synthetase (Gram-positive only)',
    side_effects: 'Local irritation, burning',
    ci: 'Hypersensitivity, large area use (polyethylene glycol base)',
    pregnancy: 'safe (category B)',
    interactions: 'None significant',
    keywords: ['T-Bact', 'mupirocin', 'impetigo cream', 'antibiotic ointment'],
  },
  {
    name: 'Betadine (Povidone-iodine)', brand: 'Betadine, Povidone, Cipladine', class: 'Topical antiseptic', schedule: 'OTC', rx_required: false,
    adult_dose: 'Apply 1-2x daily to wound area',
    indications: [{icd10: 'T14.1', label: 'Wound antisepsis'}, {icd10: 'L08.9', label: 'Skin infection (adjunct)'}],
    mechanism: 'Releases iodine, oxidizes microbial proteins/nucleic acids',
    side_effects: 'Local irritation, allergic reaction, thyroid dysfunction (extensive use)',
    ci: 'Iodine allergy, thyroid disease, pregnancy (extensive use), infants',
    pregnancy: 'safe (small areas); avoid extensive use',
    interactions: 'None significant (topical)',
    keywords: ['betadine', 'povidone iodine', 'antiseptic', 'wound wash'],
  },
  {
    name: 'Ciplox-D (Ciprofloxacin + Dexamethasone, ear/eye drops)', brand: 'Ciplox-D, Ciplox-DX, Ciprodex', class: 'Fluoroquinolone + steroid (topical)', schedule: 'H', rx_required: true,
    adult_dose: '2-3 drops q6-8h ear/eye × 5-7 days',
    indications: [{icd10: 'H66.9', label: 'Otitis externa (with infection)'}, {icd10: 'H10.9', label: 'Conjunctivitis (with infection)'}],
    mechanism: 'Antibiotic + corticosteroid for inflammation + infection',
    side_effects: 'Local irritation, ototoxicity (rare)',
    ci: 'Viral infections (HSV, VZV), perforated tympanic membrane',
    pregnancy: 'safe (category C)',
    interactions: 'None significant (topical)',
    keywords: ['ciplox-d', 'ear drops', 'eye drops', 'ciprodex'],
  },
  {
    name: 'Insulin (regular, NPH, glargine, aspart)', brand: 'Huminsulin, Mixtard, Lantus, NovoRapid, Apidra', class: 'Hormone (antidiabetic)', schedule: 'H', rx_required: true,
    adult_dose: 'Titrated to glucose targets (basal-bolus, premixed, sliding scale)',
    indications: [{icd10: 'E10.9', label: 'Type 1 DM'}, {icd10: 'E11.9', label: 'Type 2 DM (advanced)'}, {icd10: 'O24.4', label: 'Gestational DM'}],
    mechanism: 'Replaces endogenous insulin; promotes cellular glucose uptake, glycogen synthesis, lipogenesis',
    side_effects: 'Hypoglycemia, weight gain, lipodystrophy at injection site',
    ci: 'Hypoglycemia',
    pregnancy: 'safe (insulin = gold standard in pregnancy)',
    interactions: 'β-blockers (mask hypoglycemia), corticosteroids, thiazides (raise glucose), alcohol',
    keywords: ['insulin', 'lantus', 'novorapid', 'huminsulin', 'mixtard', 'diabetes medicine'],
  },
  {
    name: 'Tamoxifen', brand: 'Nolvadex, Tamodex, Valodex', class: 'Selective estrogen receptor modulator (SERM)', schedule: 'H', rx_required: true,
    adult_dose: '20 mg OD',
    indications: [{icd10: 'C50.9', label: 'Breast cancer (ER+)'}, {icd10: 'N97.0', label: 'Anovulation (off-label)'}],
    mechanism: 'Competitively blocks estrogen receptors in breast tissue',
    side_effects: 'Hot flashes, VTE risk, endometrial cancer (rare), visual changes, menstrual irregularities',
    ci: 'Pregnancy (teratogenic), history of VTE',
    pregnancy: 'CONTRAINDICATED',
    interactions: 'Warfarin, CYP2D6 inhibitors (reduce efficacy), rifampin',
    keywords: ['nolvadex', 'tamoxifen', 'SERM', 'breast cancer medicine'],
  },
];

// ================== REVERSE INDICES ==================
// Indication (text) → list of drug generic names
export const INDICATION_INDEX = (() => {
  const idx = {};
  for (const d of INDIAN_FORMULARY) {
    for (const ind of d.indications || []) {
      if (!idx[ind.label]) idx[ind.label] = [];
      if (!idx[ind.label].includes(d.name)) idx[ind.label].push(d.name);
    }
    // Also index by ICD-10 code
    for (const ind of d.indications || []) {
      if (!idx[`icd:${ind.icd10}`]) idx[`icd:${ind.icd10}`] = [];
      if (!idx[`icd:${ind.icd10}`].includes(d.name)) idx[`icd:${ind.icd10}`].push(d.name);
    }
    // Also index by class
    if (!idx[`class:${d.class}`]) idx[`class:${d.class}`] = [];
    if (!idx[`class:${d.class}`].includes(d.name)) idx[`class:${d.class}`].push(d.name);
    // Also index by drug name + brand (for search)
    idx[`name:${d.name.toLowerCase()}`] = [d.name];
    for (const b of (d.brand || '').split(',').map(s => s.trim())) {
      if (b) idx[`brand:${b.toLowerCase()}`] = [d.name];
    }
    // Index by keyword
    for (const k of d.keywords || []) {
      idx[`kw:${k.toLowerCase()}`] = [d.name];
    }
  }
  return idx;
})();

export function getDrugMonograph(generic) {
  return INDIAN_FORMULARY.find(d => d.name.toLowerCase() === generic.toLowerCase() || d.name.toLowerCase().includes(generic.toLowerCase()));
}

export function searchDrugs(q) {
  if (!q) return INDIAN_FORMULARY.slice(0, 30);
  const ql = q.toLowerCase();
  return INDIAN_FORMULARY.filter(d =>
    d.name.toLowerCase().includes(ql) ||
    (d.brand && d.brand.toLowerCase().includes(ql)) ||
    (d.class && d.class.toLowerCase().includes(ql)) ||
    (d.keywords && d.keywords.some(k => k.toLowerCase().includes(ql))) ||
    (d.indications && d.indications.some(i => i.label.toLowerCase().includes(ql)))
  ).slice(0, 50);
}

export function drugsForIndication(query) {
  const ql = query.toLowerCase().trim();
  if (!ql) return [];
  const out = new Set();
  // Match indication label keys
  for (const [key, drugs] of Object.entries(INDICATION_INDEX)) {
    if (key.startsWith('class:') || key.startsWith('name:') || key.startsWith('brand:') || key.startsWith('kw:')) continue;
    if (key.toLowerCase().includes(ql)) drugs.forEach(d => out.add(d));
  }
  // Also search across drug names/keywords for fuzzy match (e.g. "diabetes" matches "diabetes medicine" kw)
  for (const d of INDIAN_FORMULARY) {
    for (const k of d.keywords || []) {
      if (k.toLowerCase().includes(ql)) out.add(d.name);
    }
  }
  // Also match ICD-10 code description: e.g. query "diabetes" should hit E11.* codes
  if (ql.length >= 2) {
    // Check if ql matches an ICD-10 chapter keyword
    const icdMatches = {
      'diabetes': ['E10', 'E11', 'E12', 'E13', 'E14'],
      'hypertension': ['I10', 'I11', 'I12', 'I13', 'I15'],
      'asthma': ['J45', 'J46'],
      'copd': ['J44'],
      'pneumonia': ['J12', 'J13', 'J14', 'J15', 'J16', 'J17', 'J18'],
      'depression': ['F32', 'F33'],
      'anxiety': ['F40', 'F41', 'F42', 'F43'],
      'epilepsy': ['G40', 'G41'],
      'migraine': ['G43'],
      'arthritis': ['M05', 'M06', 'M15', 'M16', 'M17', 'M18', 'M19'],
      'gout': ['M10'],
      'pain': ['R52', 'M25', 'M54', 'M79', 'N94'],
      'fever': ['R50'],
      'cough': ['R05'],
      'headache': ['R51', 'G44'],
      'allergy': ['J30', 'L20', 'L50'],
      'constipation': ['K59'],
      'diarrhea': ['A09', 'K52'],
      'nausea': ['R11'],
      'anemia': ['D50', 'D51', 'D52', 'D53', 'D63', 'D64'],
      'thyroid': ['E03', 'E05', 'E07'],
      'heart failure': ['I50'],
      'angina': ['I20', 'I24'],
      'stroke': ['I63', 'I64', 'G46'],
      'uti': ['N39'],
      'kidney': ['N17', 'N18', 'N19', 'N20'],
    };
    for (const [key, codes] of Object.entries(icdMatches)) {
      if (key.includes(ql) || ql.includes(key)) {
        for (const code of codes) {
          const key2 = `icd:${code}`;
          if (INDICATION_INDEX[key2]) INDICATION_INDEX[key2].forEach(d => out.add(d));
        }
      }
    }
  }
  return [...out];
}
